import 'app_imports.dart';

final Map<String, WidgetBuilder> appRoutes = {
  SplashScreen.routeName: (ctx) => const SplashScreen(),
  LandingScreen.routeName: (ctx) => const LandingScreen(),
  HomeScreen.routeName: (ctx) => const HomeScreen(),
  StudentsDashbordScreen.routeName: (ctx) => StudentsDashbordScreen(),
  ExamScreen.routeName: (ctx) => const ExamScreen(),
  ExamResultScreen.routeName: (ctx) => const ExamResultScreen(),
  ElectronicCourseDetailScreen.routeName: (ctx) => const ElectronicCourseDetailScreen(),
  CourseAssessmentScreen.routeName: (ctx) => const CourseAssessmentScreen(),
  SimpleCoursesScreen.routeName: (ctx) => const SimpleCoursesScreen(),
  SimpleCourseDetailScreen.routeName: (ctx) => const SimpleCourseDetailScreen(),
  UserProfileScreen.routeName: (ctx) => const UserProfileScreen(),
  SupportScreen.routeName: (ctx) => const SupportScreen(),
  PresenceScreen.routeName: (ctx) => const PresenceScreen(),
  CourseShippingScreen.routeName: (ctx) => const CourseShippingScreen(),
  UserBirthCertificateScreen.routeName: (ctx) => const UserBirthCertificateScreen(),
  UserEducationScreen.routeName: (ctx) => const UserEducationScreen(),
  UserJobScreen.routeName: (ctx) => const UserJobScreen(),
  ActivitiesInfoScreen.routeName: (ctx) => const ActivitiesInfoScreen(),
  InternalPassedCoursesScreen.routeName: (ctx) => const InternalPassedCoursesScreen(),
  ExternalPassedCoursesScreen.routeName: (ctx) => const ExternalPassedCoursesScreen(),
  UniversityTeachingHistoryScreen.routeName: (ctx) => const UniversityTeachingHistoryScreen(),
  NonUniversityTeachingHistoryScreen.routeName: (ctx) => const NonUniversityTeachingHistoryScreen(),
  CompilationsAndTranslationsScreen.routeName: (ctx) => const CompilationsAndTranslationsScreen(),
  AuthScreen.routeName: (ctx) => const AuthScreen(),
};
